from pipe_iter import star_func, doublestar_func, fallible_func

def test_doublestarfunc():
    ...

def test_doublestarfunc_invalid():
    ...

def test_falliblefunc():
    ...

def test_starfunc():
    ...

def test_starfunc_invalid():
    ...

def test_stardoublestar():
    ...

def test_allfuncs():
    ...